modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="archbows"
version="${file.jarVersion}"
displayName="Arch Bows"
credits="Thanks for the tutorials Kaupenjoe"
authors="melvinbur"
description='''
a Bow Mod that extends the vanilla bow family
'''
[[dependencies.archbows]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.archbows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"